name: "gcassert"
description: "Run gcassert on your Go code"
author: "Francis Stephens"
branding:
  icon:"alert-triangle"
  color:"blue"
inputs:
outputs:
runs:
  using: "composite"
  steps:
    - name: "Run gcassert"
      id: run-gcassert
      env:
        version: ${{ inputs.version }}
      run: |
        go install github.com/jordanlewis/gcassert/cmd/gcassert@latest
        $(go env GOPATH)/bin/gcassert
      shell: bash
